name: Build ANCHA ARUMI APK from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip ANCHA_ARUMI_project_v1.1.zip -d ./project

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./project/gradlew

      - name: Build APK
        run: cd project && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ANCHA-ARUMI-APK
          path: project/app/build/outputs/apk/debug/app-debug.apk
          
